name = "CNTFormal"
version = "0.1.0"
defaultTargets = ["Foundations", "PreLevel1", "Level1", "PostLevel1PreLevel2", "Level2"]

[[lean_lib]]
name = "Foundations"
leanOptions = { autoImplicit = false, relaxedAutoImplicit = false }

[[lean_lib]]
name = "PreLevel1"
leanOptions = { autoImplicit = false, relaxedAutoImplicit = false }

[[lean_lib]]
name = "Level1"
leanOptions = { autoImplicit = false, relaxedAutoImplicit = false }

[[lean_lib]]
name = "PostLevel1PreLevel2"
leanOptions = { autoImplicit = false, relaxedAutoImplicit = false }

[[lean_lib]]
name = "Level2"
leanOptions = { autoImplicit = false, relaxedAutoImplicit = false }

[[lean_lib]]
name = "PostLevel2"
leanOptions = { autoImplicit = false, relaxedAutoImplicit = false }

[[require]]
name = "mathlib"
path = ".lake/packages/mathlib"

[[require]]
name = "physlib"
path = ".lake/packages/physlib"
