import Level1.lean.Conjectures.AxiomConsistency
import Level1.lean.Conjectures.AxiomDerivationChain
import Level1.lean.Conjectures.HPIAxiomCorrespondence
import Level1.lean.Conjectures.HPICorrection
import Level1.lean.Conjectures.IdempotentQuantization
import Level1.lean.Conjectures.Level1Transition
import Level1.lean.Conjectures.OntologicalMechanics
import Level1.lean.Conjectures.PhysicalMapping
